---
## MAJOR TODOS:
## - This works for user chmay, on Fedora 32. How much can I genericize? (e.g., create role based on OS, etc.)
##

#- name: TODO - Name me! 
#  hosts: localhost
#  connection: local
#  become: true

#  tasks:


#- name: Install packages
#  dnf:
#    name: "{{ item }}"
    # TODO: with_file for dnf is deprecated; need to learn to do the style below
    #name: "{{ query('file', ['packages.txt']) }}"
#    state: latest
#  with_items:
#    - "{{ vbox_guest_prereq_packages }}"


#
# TODO: It seems vbox guest additions is a package I can load, instead of doing the manual install??
#
#KERN_DIR=/usr/src/kernels/`uname -r`
#- name: Set kernel version
#  set_fact:
#    KERN_DIR: "/usr/src/kernels/{{ hostvars['localhost'].ansible_kernel }}"

#- name: DEBUG
#  debug:
#    var: KERN_DIR

- name: Enable sshd
  systemd:
    service: sshd.service
    enabled: yes
    state: started

- name: Open port for SSH
  firewalld:
    service: ssh
    state: enabled
    permanent: yes
    immediate: yes
